[workspace]
members = [
    "libbtrfs",
    "libbtrfs-bindings"
]
resolver = "2"

[workspace.package]
readme = "README.md"
license = "MIT"
authors = ["Lucas Wheeler <lucasww93@outlook.com>"]
repository = "https://github.com/lucasw93/libbtrfs-project"
documentation = "https://docs.rs/libbtrfs"
edition = "2024"
rust-version = "1.85"
