[package]
name = "libbtrfs"
version = "0.0.40"
description = "Rust library for working with the btrfs filesystem"
keywords = ["btrfs", "linux"]
categories = ["api-bindings", "filesystem", "os::linux-apis"]
exclude = ["TODO"]

authors.workspace = true
rust-version.workspace = true
edition.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true 

[lib]

[features]
default = ["send-stream"]
debug = []
send-stream = ["dep:crc32c", "dep:rtrb"]
use-syscalls = ["dep:syscalls"]
use-crc-fast = ['dep:crc-fast']

# deps

[dependencies.bitflags]
version = "2"

[dependencies.either]
version = "1"

[dependencies.libc]
version = "0.2.149"

[dependencies.uuid]
version = "1"

# deps - optional

[dependencies.crc32c]
optional = true
version = "0.6"

[dependencies.crc-fast]
optional = true
version = "1"

[dependencies.rtrb]
optional = true
version = "0.3"

[dependencies.syscalls]
optional = true
version = "0.8"

# dev-deps

[dev-dependencies.tempfile]
version = "3"

[lints.rust]
unsafe_op_in_unsafe_fn = "allow"
missing_docs = "warn"
